#!/usr/bin/env bash
# ============================================================
# osdb-opensuse-leap — build-distro.sh
# Generated by https://fugginold.github.io/OSDB/
# Generator Version: 2026.04.29.1
# Generated At (UTC): <TIMESTAMP>
# Builder: kiwi
# ============================================================
set -euo pipefail

DISTRO_NAME="osdb-opensuse-leap"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/var/tmp/distro-output}"
TMPDIR="${TMPDIR:-/var/tmp}"
HOST_OUTPUT_DIR="${HOST_OUTPUT_DIR:-}"
HOST_BUILD_DIR="${HOST_BUILD_DIR:-}"
LOG_FILE="${OUTPUT_DIR}/build.log"
DISPLAY_OUTPUT_DIR=""
DISPLAY_BUILD_DIR=""
DISPLAY_LOG_FILE=""
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|/work|/out|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}" || { log "Cleanup failed for path: ${cleanup_path}"; return 1; }
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${DISPLAY_LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${DISPLAY_LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${DISPLAY_LOG_FILE}"
  log "Build directory: ${DISPLAY_BUILD_DIR}"
  log "Output directory: ${DISPLAY_OUTPUT_DIR}"
  log "Temp directory: ${TMPDIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="opensuse/tumbleweed"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${BUILD_DIR}"):/work" \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/work/distro-build \
    -e OUTPUT_DIR=/out \
    -e TMPDIR=/var/tmp \
    -e HOST_BUILD_DIR="$(realpath "${BUILD_DIR}")" \
    -e HOST_OUTPUT_DIR="$(realpath "${OUTPUT_DIR}")" \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
mkdir -p "${TMPDIR}"
TMPDIR="$(cd "${TMPDIR}" && pwd -P)"
export TMPDIR TMP="${TMPDIR}" TEMP="${TMPDIR}"
LOG_FILE="${OUTPUT_DIR}/build.log"
if [ -n "${HOST_OUTPUT_DIR}" ]; then
  DISPLAY_OUTPUT_DIR="${HOST_OUTPUT_DIR}"
else
  DISPLAY_OUTPUT_DIR="${OUTPUT_DIR}"
fi
if [ -n "${HOST_BUILD_DIR}" ]; then
  DISPLAY_BUILD_DIR="${HOST_BUILD_DIR}"
else
  DISPLAY_BUILD_DIR="${BUILD_DIR}"
fi
DISPLAY_LOG_FILE="${DISPLAY_OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

KIWI_DESC="${BUILD_DIR}/kiwi-desc"
OPENSUSE_MIRROR="https://download.opensuse.org/distribution/leap/15.6/repo/oss/"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing KIWI..."
if ! command -v kiwi-ng >/dev/null 2>&1; then
  zypper --non-interactive refresh
  zypper --non-interactive install -y kiwi-ng ||     zypper --non-interactive install -y python3-kiwi ||     zypper --non-interactive install -y kiwi || true
fi
if ! command -v kiwi-ng >/dev/null 2>&1; then
  die "kiwi-ng is unavailable after package installation attempts (kiwi-ng/python3-kiwi/kiwi)."
fi

# ── KIWI image description ─────────────────────────────────────
log "Writing KIWI image description..."
mkdir -p "${KIWI_DESC}"

cat > "${KIWI_DESC}/config.xml" << 'XML_EOF'
<?xml version="1.0" encoding="utf-8"?>
<image schemaversion="7.4" name="osdb-opensuse-leap">
  <description type="system">
    <author>Distro Builder Wizard</author>
    <contact>contact@example.com</contact>
    <specification>osdb-opensuse-leap — generated by OSDB wizard</specification>
  </description>
  <preferences>
    <version>1.0.0</version>
    <packagemanager>zypper</packagemanager>
    <type image="iso" flags="overlay" firmware="efi">
      <bootloader name="grub2"/>
    </type>
  </preferences>
  <repository type="rpm-md" alias="openSUSE-leap">
    <source path="${OPENSUSE_MIRROR}"/>
  </repository>
  <packages type="image">
    <package name="patterns-openSUSE-base"/>
    <package name="patterns-kde-kde_x11"/>
    <package name="sddm"/>
    <package name="firefox"/>
    <package name="vlc"/>
    <package name="git"/>
    <package name="cups"/>
    <package name="NetworkManager"/>
    <package name="cups"/>
    <package name="bluez"/>
  </packages>
  <packages type="bootstrap">
    <package name="glibc-locale"/>
    <package name="ca-certificates"/>
  </packages>
</image>
XML_EOF

cat > "${KIWI_DESC}/config.sh" << 'CFG_EOF'
#!/bin/bash
# Called inside the image chroot during build
set -e
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi

# Auto-login hook (SDDM)
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf << 'SDDM_EOF'
[Autologin]
User=user
Session=plasma
SDDM_EOF
CFG_EOF
chmod +x "${KIWI_DESC}/config.sh"


FALLBACK_MIRRORS=("https://mirrorcache.opensuse.org/download")


# ── Self-Healing Mirror Configuration ────────────────────────
PRIMARY_MIRROR="https://download.opensuse.org/distribution/leap/15.6/repo/oss/"
MAX_RETRIES_PER_MIRROR=2
MIRRORS_TRIED=()

is_checksum_failure() {
  grep -qE '(Checksum error|checksum|downloads+error|Failed to download|Signature verification failed|Repository.*is invalid)' "$build_log"
}

build_with_mirror() {
  local mirror_url="$1"
  OPENSUSE_MIRROR="$mirror_url"

  log "Building openSUSE image (this may take 30–60 minutes)..."

build_log="$(mktemp)"
kiwi-ng --profile Standard system build \
  --description "$KIWI_DESC" \
  --target-dir "$OUTPUT_DIR" 2>&1 | tee "$build_log"
}

log "Starting self-healing build with primary mirror: ${PRIMARY_MIRROR}"

attempt=0
while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
  if [ "$attempt" -gt 0 ]; then
    log "Retrying primary mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${PRIMARY_MIRROR}"
    rm -rf "$KIWI_DESC" "$OUTPUT_DIR"/*.iso
  else
    log "Attempting build with primary mirror: ${PRIMARY_MIRROR}"
  fi

  MIRRORS_TRIED+=("${PRIMARY_MIRROR}")
  build_with_mirror "${PRIMARY_MIRROR}"; result=$?

  if [ "$result" -eq 0 ]; then
    rm -f "$build_log"
log "Generating SHA256 checksum..."
sha256sum "$OUTPUT_DIR"/*.iso > "$OUTPUT_DIR/$DISTRO_NAME.iso.sha256" 2>/dev/null || true
KIWI_ISO=$(find "$OUTPUT_DIR" -maxdepth 1 -name '*.iso' | head -1)

log "Build complete!"
log "ISO:      $KIWI_ISO"
log "Checksum: $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
    exit 0
  fi

  if [ "$result" -ne 2 ]; then
    log "Build failed with non-checksum error. Not retrying."
    exit "$result"
  fi

  log "Checksum failure detected on primary mirror"
  attempt=$((attempt + 1))
done

log "Primary mirror exhausted after $((MAX_RETRIES_PER_MIRROR + 1)) attempts"

for fallback_mirror in "${FALLBACK_MIRRORS[@]}"; do
  log "Switching to fallback mirror: ${fallback_mirror}"
  rm -rf "$KIWI_DESC" "$OUTPUT_DIR"/*.iso

  attempt=0
  while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
    if [ "$attempt" -gt 0 ]; then
      log "Retrying fallback mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${fallback_mirror}"
      rm -rf "$KIWI_DESC" "$OUTPUT_DIR"/*.iso
    fi

    MIRRORS_TRIED+=("${fallback_mirror}")
    build_with_mirror "${fallback_mirror}"; result=$?

    if [ "$result" -eq 0 ]; then
      rm -f "$build_log"
log "Generating SHA256 checksum..."
sha256sum "$OUTPUT_DIR"/*.iso > "$OUTPUT_DIR/$DISTRO_NAME.iso.sha256" 2>/dev/null || true
KIWI_ISO=$(find "$OUTPUT_DIR" -maxdepth 1 -name '*.iso' | head -1)

log "Build complete!"
log "ISO:      $KIWI_ISO"
log "Checksum: $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
      exit 0
    fi

    if [ "$result" -ne 2 ]; then
      log "Build failed with non-checksum error. Not retrying."
      exit "$result"
    fi

    log "Checksum failure detected on fallback mirror: ${fallback_mirror}"
    attempt=$((attempt + 1))
  done

  log "Fallback mirror exhausted: ${fallback_mirror}"
done

log "All mirrors exhausted after checksum failures. Mirrors tried:"
for m in "${MIRRORS_TRIED[@]}"; do
  log "  - ${m}"
done
die "Build failed after exhausting all mirrors"

