#!/usr/bin/env bash
# ============================================================
# osdb-rpios-lite-bookworm — build-distro.sh
# Generated by https://fugginold.github.io/OSDB/
# Generator Version: 2026.04.29.1
# Generated At (UTC): <TIMESTAMP>
# Builder: pi-gen
# ============================================================
set -euo pipefail

DISTRO_NAME="osdb-rpios-lite-bookworm"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/var/tmp/distro-output}"
TMPDIR="${TMPDIR:-/var/tmp}"
HOST_OUTPUT_DIR="${HOST_OUTPUT_DIR:-}"
HOST_BUILD_DIR="${HOST_BUILD_DIR:-}"
LOG_FILE="${OUTPUT_DIR}/build.log"
DISPLAY_OUTPUT_DIR=""
DISPLAY_BUILD_DIR=""
DISPLAY_LOG_FILE=""
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|/work|/out|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}" || { log "Cleanup failed for path: ${cleanup_path}"; return 1; }
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${DISPLAY_LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${DISPLAY_LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${DISPLAY_LOG_FILE}"
  log "Build directory: ${DISPLAY_BUILD_DIR}"
  log "Output directory: ${DISPLAY_OUTPUT_DIR}"
  log "Temp directory: ${TMPDIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="debian:bookworm"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${BUILD_DIR}"):/work" \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/work/distro-build \
    -e OUTPUT_DIR=/out \
    -e TMPDIR=/var/tmp \
    -e HOST_BUILD_DIR="$(realpath "${BUILD_DIR}")" \
    -e HOST_OUTPUT_DIR="$(realpath "${OUTPUT_DIR}")" \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
mkdir -p "${TMPDIR}"
TMPDIR="$(cd "${TMPDIR}" && pwd -P)"
export TMPDIR TMP="${TMPDIR}" TEMP="${TMPDIR}"
LOG_FILE="${OUTPUT_DIR}/build.log"
if [ -n "${HOST_OUTPUT_DIR}" ]; then
  DISPLAY_OUTPUT_DIR="${HOST_OUTPUT_DIR}"
else
  DISPLAY_OUTPUT_DIR="${OUTPUT_DIR}"
fi
if [ -n "${HOST_BUILD_DIR}" ]; then
  DISPLAY_BUILD_DIR="${HOST_BUILD_DIR}"
else
  DISPLAY_BUILD_DIR="${BUILD_DIR}"
fi
DISPLAY_LOG_FILE="${DISPLAY_OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

PIGEN_DIR="${BUILD_DIR}/pi-gen"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing pi-gen dependencies..."
apt-get update -qq
apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree \
  zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git \
  curl bc gpg


FALLBACK_MIRRORS=("https://github.com/raspberrypi/pi-gen.git")


# ── Self-Healing Mirror Configuration ────────────────────────
PRIMARY_MIRROR="https://github.com/RPi-Distro/pi-gen.git"
MAX_RETRIES_PER_MIRROR=2
MIRRORS_TRIED=()

is_checksum_failure() {
  grep -qE '(checksum|Checksum|hash|Hash|sha256|sha1|Digest|BADs+signature|Signature verification failed|404|Not Found|RPC failed|HTTP.*5dd)' "$build_log"
}

build_with_mirror() {
  local mirror_url="$1"
  PIGEN_GIT_URL="$mirror_url"

  # ── Clone pi-gen ──────────────────────────────────────────────
log "Cloning pi-gen..."

build_log="$(mktemp)"

if [ -d "$PIGEN_DIR/.git" ]; then
  git -C "$PIGEN_DIR" remote set-url origin "$PIGEN_GIT_URL" 2>&1 | tee "$build_log"
  git -C "$PIGEN_DIR" pull 2>&1 | tee -a "$build_log"
else
  git clone "$PIGEN_GIT_URL" "$PIGEN_DIR" 2>&1 | tee "$build_log"
fi

cd "$PIGEN_DIR"
}

log "Starting self-healing build with primary mirror: ${PRIMARY_MIRROR}"

attempt=0
while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
  if [ "$attempt" -gt 0 ]; then
    log "Retrying primary mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${PRIMARY_MIRROR}"
    rm -rf "$PIGEN_DIR"
  else
    log "Attempting build with primary mirror: ${PRIMARY_MIRROR}"
  fi

  MIRRORS_TRIED+=("${PRIMARY_MIRROR}")
  build_with_mirror "${PRIMARY_MIRROR}"; result=$?

  if [ "$result" -eq 0 ]; then
    rm -f "$build_log"
    exit 0
  fi

  if [ "$result" -ne 2 ]; then
    log "Build failed with non-checksum error. Not retrying."
    exit "$result"
  fi

  log "Checksum failure detected on primary mirror"
  attempt=$((attempt + 1))
done

log "Primary mirror exhausted after $((MAX_RETRIES_PER_MIRROR + 1)) attempts"

for fallback_mirror in "${FALLBACK_MIRRORS[@]}"; do
  log "Switching to fallback mirror: ${fallback_mirror}"
  rm -rf "$PIGEN_DIR"

  attempt=0
  while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
    if [ "$attempt" -gt 0 ]; then
      log "Retrying fallback mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${fallback_mirror}"
      rm -rf "$PIGEN_DIR"
    fi

    MIRRORS_TRIED+=("${fallback_mirror}")
    build_with_mirror "${fallback_mirror}"; result=$?

    if [ "$result" -eq 0 ]; then
      rm -f "$build_log"
      exit 0
    fi

    if [ "$result" -ne 2 ]; then
      log "Build failed with non-checksum error. Not retrying."
      exit "$result"
    fi

    log "Checksum failure detected on fallback mirror: ${fallback_mirror}"
    attempt=$((attempt + 1))
  done

  log "Fallback mirror exhausted: ${fallback_mirror}"
done

log "All mirrors exhausted after checksum failures. Mirrors tried:"
for m in "${MIRRORS_TRIED[@]}"; do
  log "  - ${m}"
done
die "Build failed after exhausting all mirrors"


# ── User password ─────────────────────────────────────────────
# Set PIGEN_USER_PASS env var before running, or it defaults to "raspberry".
# WARNING: the default password is insecure — change it for production images.
: "${PIGEN_USER_PASS:=raspberry}"

# ── Main config ───────────────────────────────────────────────
log "Writing pi-gen config..."
cat > config << CONFIG_EOF
IMG_NAME="osdb-rpios-lite-bookworm"
RELEASE="bookworm"
LOCALE_DEFAULT="en_US.UTF-8"
KEYBOARD_KEYMAP="us"
KEYBOARD_LAYOUT="English (US)"
TIMEZONE_DEFAULT="America/New_York"
FIRST_USER_NAME="pi"
FIRST_USER_PASS="${PIGEN_USER_PASS}"
ENABLE_SSH=1
STAGE_LIST="stage0 stage1 stage2 stage-custom"
CONFIG_EOF

# ── Skip stages not needed ────────────────────────────────────
touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES

# ── Custom stage: packages ────────────────────────────────────
log "Writing custom stage..."
mkdir -p stage-custom/01-packages
EXTRA_PKGS="chromium-browser git raspi-config rpi-eeprom network-manager cups bluez openssh-server unattended-upgrades rpi-eeprom raspi-config"
printf '%s' "${EXTRA_PKGS}" > stage-custom/01-packages/packages

# ── Custom stage: services + config.txt ──────────────────────
mkdir -p stage-custom/03-run
cat > stage-custom/03-run/01-run.sh << 'RUN_EOF'
#!/bin/bash
on_chroot << 'CHROOT'
set -e

# Enable services
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "ssh.service" 2>/dev/null | grep -q "^ssh.service"; then
  systemctl enable "ssh.service"
else
  echo "Skipping ssh.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "unattended-upgrades.service" 2>/dev/null | grep -q "^unattended-upgrades.service"; then
  systemctl enable "unattended-upgrades.service"
else
  echo "Skipping unattended-upgrades.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "rpi-eeprom-update.service" 2>/dev/null | grep -q "^rpi-eeprom-update.service"; then
  systemctl enable "rpi-eeprom-update.service"
else
  echo "Skipping rpi-eeprom-update.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "raspi-config.service" 2>/dev/null | grep -q "^raspi-config.service"; then
  systemctl enable "raspi-config.service"
else
  echo "Skipping raspi-config.service (unit not found - package may not be installed)"
fi

# config.txt flags
CONFIG_TXT="/boot/firmware/config.txt"
[ -f "${CONFIG_TXT}" ] || CONFIG_TXT="/boot/config.txt"
echo "arm_64bit=1" >> "${CONFIG_TXT}"
echo "gpu_mem=128" >> "${CONFIG_TXT}"
CHROOT
RUN_EOF
chmod +x stage-custom/03-run/01-run.sh

# ── Build ──────────────────────────────────────────────────────
log "Starting pi-gen build (this may take 30–90 minutes)..."
sudo ./build.sh

# ── Copy output ────────────────────────────────────────────────
LATEST_XZ=$(find deploy -name '*.img.xz' | head -1)
LATEST_IMG=$(find deploy -name '*.img' -not -name '*.img.xz' | head -1)
[ -n "${LATEST_XZ}"  ] && cp "${LATEST_XZ}"  "${OUTPUT_DIR}/${DISTRO_NAME}.img.xz" || true
[ -n "${LATEST_IMG}" ] && cp "${LATEST_IMG}" "${OUTPUT_DIR}/${DISTRO_NAME}.img"    || true

log "Build complete!"
log "Image:    ${OUTPUT_DIR}/${DISTRO_NAME}.img.xz"
log ""
log "# Flash to SD card (replace /dev/sdX with your device):"
log "# xzcat ${OUTPUT_DIR}/${DISTRO_NAME}.img.xz | sudo dd of=/dev/sdX bs=4M status=progress conv=fsync"
