#!/usr/bin/env bash
# ============================================================
# osdb-ubuntu-2404 — build-distro.sh
# Generated by https://fugginold.github.io/OSDB/
# Generator Version: 2026.04.29.1
# Generated At (UTC): <TIMESTAMP>
# Builder: live-build
# ============================================================
set -euo pipefail

DISTRO_NAME="osdb-ubuntu-2404"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/var/tmp/distro-output}"
TMPDIR="${TMPDIR:-/var/tmp}"
HOST_OUTPUT_DIR="${HOST_OUTPUT_DIR:-}"
HOST_BUILD_DIR="${HOST_BUILD_DIR:-}"
LOG_FILE="${OUTPUT_DIR}/build.log"
DISPLAY_OUTPUT_DIR=""
DISPLAY_BUILD_DIR=""
DISPLAY_LOG_FILE=""
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|/work|/out|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}" || { log "Cleanup failed for path: ${cleanup_path}"; return 1; }
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${DISPLAY_LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${DISPLAY_LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${DISPLAY_LOG_FILE}"
  log "Build directory: ${DISPLAY_BUILD_DIR}"
  log "Output directory: ${DISPLAY_OUTPUT_DIR}"
  log "Temp directory: ${TMPDIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="ubuntu:noble"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${BUILD_DIR}"):/work" \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/work/distro-build \
    -e OUTPUT_DIR=/out \
    -e TMPDIR=/var/tmp \
    -e HOST_BUILD_DIR="$(realpath "${BUILD_DIR}")" \
    -e HOST_OUTPUT_DIR="$(realpath "${OUTPUT_DIR}")" \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
mkdir -p "${TMPDIR}"
TMPDIR="$(cd "${TMPDIR}" && pwd -P)"
export TMPDIR TMP="${TMPDIR}" TEMP="${TMPDIR}"
LOG_FILE="${OUTPUT_DIR}/build.log"
if [ -n "${HOST_OUTPUT_DIR}" ]; then
  DISPLAY_OUTPUT_DIR="${HOST_OUTPUT_DIR}"
else
  DISPLAY_OUTPUT_DIR="${OUTPUT_DIR}"
fi
if [ -n "${HOST_BUILD_DIR}" ]; then
  DISPLAY_BUILD_DIR="${HOST_BUILD_DIR}"
else
  DISPLAY_BUILD_DIR="${BUILD_DIR}"
fi
DISPLAY_LOG_FILE="${DISPLAY_OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

LB_DIR="${BUILD_DIR}/lb"
ensure_live_build_workdir() {
  local path="$1"
  local mount_opts

  mkdir -p "${path}"
  if ! command -v findmnt >/dev/null 2>&1; then
    return 0
  fi

  mount_opts="$(findmnt -T "${path}" -no OPTIONS 2>/dev/null || true)"
  case ",${mount_opts}," in
    *,nodev,*|*,noexec,*)
      die "BUILD_DIR '${path}' is on a filesystem mounted with ${mount_opts}. live-build/debootstrap needs device nodes and executable scripts. Re-run with BUILD_DIR=/var/tmp/distro-build or another path on a dev,exec filesystem."
      ;;
  esac
}

ensure_live_build_workdir "${BUILD_DIR}"

ensure_ubuntu_archive_signing_keys() {
  local keyring="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
  local archive_key="871920D1991BC93C"

  command -v gpg >/dev/null 2>&1 || return 0
  if gpg --batch --no-default-keyring --keyring "$keyring" --list-keys "$archive_key" >/dev/null 2>&1; then
    return 0
  fi

  log "Importing missing Ubuntu archive signing key: $archive_key"
  gpg --batch --keyserver hkp://keyserver.ubuntu.com:80     --no-default-keyring --keyring "$keyring" --recv-keys "$archive_key" || true
}

apt_update_with_key_repair() {
  if apt-get update -qq; then
    return 0
  fi

  log "apt-get update failed; attempting Ubuntu key repair and retry..."
  ensure_ubuntu_archive_signing_keys
  rm -rf /var/lib/apt/lists/*
  apt-get clean
  apt-get update -qq
}

# ── Prerequisites ─────────────────────────────────────────────
log "Installing live-build..."
apt_update_with_key_repair
DEBIAN_FRONTEND=noninteractive apt-get install -y live-build curl ca-certificates xz-utils
DEBIAN_FRONTEND=noninteractive apt-get install -y syslinux-utils || DEBIAN_FRONTEND=noninteractive apt-get install -y syslinux isolinux

if ! command -v isohybrid >/dev/null 2>&1; then
  for cand in /usr/lib/ISOLINUX/isohybrid /usr/lib/syslinux/isohybrid; do
    if [ -x "$cand" ]; then
      ln -sf "$cand" /usr/local/bin/isohybrid
      break
    fi
  done
fi

if ! command -v isohybrid >/dev/null 2>&1; then
  die "isohybrid is required for iso-hybrid output but is not installed. Install syslinux-utils (or syslinux/isolinux) in the build container."
fi

# ── Self-Healing Mirror Configuration ────────────────────────
# Array of fallback mirrors to try if primary mirror has checksum failures
FALLBACK_MIRRORS=("http://us.archive.ubuntu.com/ubuntu" "http://uk.archive.ubuntu.com/ubuntu")

# Function to configure and build with a specific mirror
build_with_mirror() {
  local mirror_url="$1"
  log "Configuring live-build with mirror: ${mirror_url}"

  mkdir -p "${LB_DIR}"
  cd "${LB_DIR}"

  # ── lb config ─────────────────────────────────────────────────
  lb config \
    --distribution "noble" \
    --archive-areas "main restricted universe multiverse" \
    --mirror-bootstrap "${mirror_url}" \
    --mirror-binary "${mirror_url}" \
    --mode ubuntu \
    --parent-mirror-bootstrap "${mirror_url}" \
    --parent-mirror-chroot "${mirror_url}" \
    --parent-mirror-binary "${mirror_url}" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --mirror-chroot "${mirror_url}" \
    --binary-images iso \
    --bootloader "grub-efi,syslinux" \
    --debian-installer false \
    --apt-recommends false \
    --memtest none

  # ── Chroot environment ──────────────────────────────────────────────
  log "Setting noninteractive environment for chroot..."
  mkdir -p config
  printf '%s\n' \
    'DEBIAN_FRONTEND=noninteractive' \
    'DEBCONF_NONINTERACTIVE_SEEN=true' > config/environment.chroot

  # ── Debconf preseed ──────────────────────────────────────────────
  log "Writing debconf preseed..."
  mkdir -p config/preseed
  cat > config/preseed/live.cfg.chroot << 'PRESEED_EOF'
console-setup console-setup/charmap47 select UTF-8
console-setup console-setup/codeset47 select Guess optimal character set
console-setup console-setup/fontface47 select Fixed
console-setup console-setup/fontsize-fb47 select 8x16
console-setup console-setup/store_defaults_in_debconf_db boolean true
keyboard-configuration keyboard-configuration/modelcode string pc105
keyboard-configuration keyboard-configuration/layout select English (US)
keyboard-configuration keyboard-configuration/layoutcode string us
keyboard-configuration keyboard-configuration/variant select
keyboard-configuration keyboard-configuration/variantcode string
keyboard-configuration keyboard-configuration/xkb-keymap select us
PRESEED_EOF

  # ── Package lists ──────────────────────────────────────────────
  log "Writing package lists..."
  mkdir -p config/package-lists
  printf '%s\n' "gnome-shell" "gnome-session" "gdm3" "gnome-control-center" "nautilus" > config/package-lists/desktop.list.chroot
  printf '%s\n' "firefox" "vlc" "git" "cups" > config/package-lists/user.list.chroot
  printf '%s\n' "network-manager" "cups" "bluez" "unattended-upgrades" > config/package-lists/services.list.chroot
  printf '%s\n' "live-boot" "live-config" "live-config-systemd" > config/package-lists/live.list.chroot
  
  

  # ── Chroot hooks ───────────────────────────────────────────────
  log "Writing chroot hooks..."
  mkdir -p config/hooks/live

  # ── PPAs ──────────────────────────────────────────────────────
  # No PPAs configured

  # Hook: enable services
  cat > config/hooks/live/0010-services.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "unattended-upgrades.service" 2>/dev/null | grep -q "^unattended-upgrades.service"; then
  systemctl enable "unattended-upgrades.service"
else
  echo "Skipping unattended-upgrades.service (unit not found - package may not be installed)"
fi
HOOK_EOF
  chmod +x config/hooks/live/0010-services.hook.chroot

  # Hook: display manager / auto-login
  cat > config/hooks/live/0020-autologin.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e

# Auto-login hook (GDM)
mkdir -p /etc/gdm3
cat > /etc/gdm3/custom.conf << 'GDM_EOF'
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=user
GDM_EOF
HOOK_EOF
  chmod +x config/hooks/live/0020-autologin.hook.chroot



  # ── Build ──────────────────────────────────────────────────────
  log "Starting live-build (this may take 30–60 minutes)..."
  local build_log
  build_log="$(mktemp)"

  # Run lb build and capture output for checksum failure detection
  if lb build 2>&1 | tee "${build_log}"; then
    rm -f "${build_log}"
    return 0
  else
    # Check if failure is due to checksum mismatch
    if grep -qE '(Hash Sum mismatch|Hash mismatch)' "${build_log}"; then
      rm -f "${build_log}"
      return 1  # Checksum failure - retry possible
    else
      rm -f "${build_log}"
      return 2  # Non-checksum failure - do not retry
    fi
  fi
}


# ── Self-Healing Mirror Configuration ────────────────────────
PRIMARY_MIRROR="http://archive.ubuntu.com/ubuntu"
MAX_RETRIES_PER_MIRROR=2
MIRRORS_TRIED=()

is_checksum_failure() {
  grep -qE '(Hash Sum mismatch|Hash mismatch)' "$build_log"
}

build_with_mirror() {
  local mirror_url="$1"
  log "Configuring live-build with mirror: $mirror_url"

  mkdir -p "$LB_DIR"
  cd "$LB_DIR"

  lb config \
    --distribution "noble" \
    --archive-areas "main restricted universe multiverse" \
    --mirror-bootstrap "$mirror_url" \
    --mirror-binary "$mirror_url" \
    --mode ubuntu \
    --parent-mirror-bootstrap "$mirror_url" \
    --parent-mirror-chroot "$mirror_url" \
    --parent-mirror-binary "$mirror_url" \
    --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --mirror-chroot-security "http://security.ubuntu.com/ubuntu" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --mirror-chroot "$mirror_url" \
    --binary-images iso \
    --bootloader "grub-efi,syslinux" \
    --debian-installer false \
    --apt-recommends false \
    --memtest none

  log "Setting noninteractive environment for chroot..."
  mkdir -p config
  printf '%s\n' \
    'DEBIAN_FRONTEND=noninteractive' \
    'DEBCONF_NONINTERACTIVE_SEEN=true' > config/environment.chroot

  log "Writing debconf preseed..."
  mkdir -p config/preseed

  log "Writing chroot hooks..."
  mkdir -p config/hooks/live

  # No PPAs configured

  cat > config/hooks/live/0010-services.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "unattended-upgrades.service" 2>/dev/null | grep -q "^unattended-upgrades.service"; then
  systemctl enable "unattended-upgrades.service"
else
  echo "Skipping unattended-upgrades.service (unit not found - package may not be installed)"
fi
HOOK_EOF
  chmod +x config/hooks/live/0010-services.hook.chroot

  cat > config/hooks/live/0020-autologin.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e

# Auto-login hook (GDM)
mkdir -p /etc/gdm3
cat > /etc/gdm3/custom.conf << 'GDM_EOF'
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=user
GDM_EOF
HOOK_EOF
  chmod +x config/hooks/live/0020-autologin.hook.chroot



  log "Starting live-build (this may take 30–60 minutes)..."
  build_log="$(mktemp)"

  lb build 2>&1 | tee "$build_log"
}

log "Starting self-healing build with primary mirror: ${PRIMARY_MIRROR}"

attempt=0
while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
  if [ "$attempt" -gt 0 ]; then
    log "Retrying primary mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${PRIMARY_MIRROR}"
    cd /
cleanup_build_dir || die "Cleanup failed before retry; cannot guarantee clean state."
mkdir -p "$BUILD_DIR"
: > "$BUILD_MARKER"
  else
    log "Attempting build with primary mirror: ${PRIMARY_MIRROR}"
  fi

  MIRRORS_TRIED+=("${PRIMARY_MIRROR}")
  build_with_mirror "${PRIMARY_MIRROR}"; result=$?

  if [ "$result" -eq 0 ]; then
    rm -f "$build_log"
cd "$LB_DIR"
find . -maxdepth 1 -name '*.iso' -exec mv {} "$OUTPUT_DIR/$DISTRO_NAME.iso" \;
log "Generating SHA256 checksum..."
sha256sum "$OUTPUT_DIR/$DISTRO_NAME.iso" > "$OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
log "Build complete!"
log "ISO:      $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso"
log "Checksum: $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
    exit 0
  fi

  if [ "$result" -ne 2 ]; then
    log "Build failed with non-checksum error. Not retrying."
    exit "$result"
  fi

  log "Checksum failure detected on primary mirror"
  attempt=$((attempt + 1))
done

log "Primary mirror exhausted after $((MAX_RETRIES_PER_MIRROR + 1)) attempts"

for fallback_mirror in "${FALLBACK_MIRRORS[@]}"; do
  log "Switching to fallback mirror: ${fallback_mirror}"
  cd /
cleanup_build_dir || die "Cleanup failed before retry; cannot guarantee clean state."
mkdir -p "$BUILD_DIR"
: > "$BUILD_MARKER"

  attempt=0
  while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
    if [ "$attempt" -gt 0 ]; then
      log "Retrying fallback mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${fallback_mirror}"
      cd /
cleanup_build_dir || die "Cleanup failed before retry; cannot guarantee clean state."
mkdir -p "$BUILD_DIR"
: > "$BUILD_MARKER"
    fi

    MIRRORS_TRIED+=("${fallback_mirror}")
    build_with_mirror "${fallback_mirror}"; result=$?

    if [ "$result" -eq 0 ]; then
      rm -f "$build_log"
cd "$LB_DIR"
find . -maxdepth 1 -name '*.iso' -exec mv {} "$OUTPUT_DIR/$DISTRO_NAME.iso" \;
log "Generating SHA256 checksum..."
sha256sum "$OUTPUT_DIR/$DISTRO_NAME.iso" > "$OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
log "Build complete!"
log "ISO:      $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso"
log "Checksum: $DISPLAY_OUTPUT_DIR/$DISTRO_NAME.iso.sha256"
      exit 0
    fi

    if [ "$result" -ne 2 ]; then
      log "Build failed with non-checksum error. Not retrying."
      exit "$result"
    fi

    log "Checksum failure detected on fallback mirror: ${fallback_mirror}"
    attempt=$((attempt + 1))
  done

  log "Fallback mirror exhausted: ${fallback_mirror}"
done

log "All mirrors exhausted after checksum failures. Mirrors tried:"
for m in "${MIRRORS_TRIED[@]}"; do
  log "  - ${m}"
done
die "Build failed after exhausting all mirrors"

