#!/usr/bin/env bash
# ============================================================
# osdb-ubuntu-rpi-2404 — build-distro.sh
# Generated by https://fugginold.github.io/OSDB/
# Generator Version: 2026.04.29.1
# Generated At (UTC): <TIMESTAMP>
# Builder: ubuntu-rpi
# ============================================================
set -euo pipefail

DISTRO_NAME="osdb-ubuntu-rpi-2404"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/var/tmp/distro-output}"
TMPDIR="${TMPDIR:-/var/tmp}"
HOST_OUTPUT_DIR="${HOST_OUTPUT_DIR:-}"
HOST_BUILD_DIR="${HOST_BUILD_DIR:-}"
LOG_FILE="${OUTPUT_DIR}/build.log"
DISPLAY_OUTPUT_DIR=""
DISPLAY_BUILD_DIR=""
DISPLAY_LOG_FILE=""
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|/work|/out|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}" || { log "Cleanup failed for path: ${cleanup_path}"; return 1; }
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${DISPLAY_LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${DISPLAY_LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${DISPLAY_LOG_FILE}"
  log "Build directory: ${DISPLAY_BUILD_DIR}"
  log "Output directory: ${DISPLAY_OUTPUT_DIR}"
  log "Temp directory: ${TMPDIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="ubuntu:noble"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${BUILD_DIR}"):/work" \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/work/distro-build \
    -e OUTPUT_DIR=/out \
    -e TMPDIR=/var/tmp \
    -e HOST_BUILD_DIR="$(realpath "${BUILD_DIR}")" \
    -e HOST_OUTPUT_DIR="$(realpath "${OUTPUT_DIR}")" \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
mkdir -p "${TMPDIR}"
TMPDIR="$(cd "${TMPDIR}" && pwd -P)"
export TMPDIR TMP="${TMPDIR}" TEMP="${TMPDIR}"
LOG_FILE="${OUTPUT_DIR}/build.log"
if [ -n "${HOST_OUTPUT_DIR}" ]; then
  DISPLAY_OUTPUT_DIR="${HOST_OUTPUT_DIR}"
else
  DISPLAY_OUTPUT_DIR="${OUTPUT_DIR}"
fi
if [ -n "${HOST_BUILD_DIR}" ]; then
  DISPLAY_BUILD_DIR="${HOST_BUILD_DIR}"
else
  DISPLAY_BUILD_DIR="${BUILD_DIR}"
fi
DISPLAY_LOG_FILE="${DISPLAY_OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

ROOTFS="${BUILD_DIR}/rootfs"
IMG_SIZE="8G"
IMG_FILE="${OUTPUT_DIR}/${DISTRO_NAME}.img"
APT_MIRROR="http://ports.ubuntu.com/ubuntu-ports"

FALLBACK_MIRRORS_RAW=("http://us.archive.ubuntu.com/ubuntu" "http://uk.archive.ubuntu.com/ubuntu")
FALLBACK_MIRRORS=()
for m in "${FALLBACK_MIRRORS_RAW[@]}"; do
  [ "$m" = "http://ports.ubuntu.com/ubuntu-ports" ] && continue
  FALLBACK_MIRRORS+=("${m}")
done

ensure_ubuntu_archive_signing_keys() {
  local keyring="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
  local archive_key="871920D1991BC93C"

  command -v gpg >/dev/null 2>&1 || return 0
  if gpg --batch --no-default-keyring --keyring "$keyring" --list-keys "$archive_key" >/dev/null 2>&1; then
    return 0
  fi

  log "Importing missing Ubuntu archive signing key: $archive_key"
  gpg --batch --keyserver hkp://keyserver.ubuntu.com:80     --no-default-keyring --keyring "$keyring" --recv-keys "$archive_key" || true
}

apt_update_with_key_repair() {
  if apt-get update -qq; then
    return 0
  fi

  log "apt-get update failed; attempting Ubuntu key repair and retry..."
  ensure_ubuntu_archive_signing_keys
  rm -rf /var/lib/apt/lists/*
  apt-get clean
  apt-get update -qq
}

# ── Prerequisites ─────────────────────────────────────────────
log "Installing build dependencies..."
apt_update_with_key_repair
apt-get install -y debootstrap qemu-user-static binfmt-support parted \
  dosfstools kpartx losetup rsync curl

# ── Create image file ─────────────────────────────────────────
log "Creating ${IMG_SIZE} image file..."
truncate -s "${IMG_SIZE}" "${IMG_FILE}"

# Partition: FAT32 boot (256 MB) + ext4 root
parted -s "${IMG_FILE}" mklabel msdos
parted -s "${IMG_FILE}" mkpart primary fat32 1MiB 257MiB
parted -s "${IMG_FILE}" set 1 boot on
parted -s "${IMG_FILE}" mkpart primary ext4 257MiB 100%

# Loop device
LOOP_DEV=$(losetup --show -fP "${IMG_FILE}")
mkfs.vfat -F32 "${LOOP_DEV}p1"
mkfs.ext4 -F "${LOOP_DEV}p2"

# Mount
mkdir -p "${ROOTFS}"
mount "${LOOP_DEV}p2" "${ROOTFS}"
mkdir -p "${ROOTFS}/boot/firmware"
mount "${LOOP_DEV}p1" "${ROOTFS}/boot/firmware"



# ── Self-Healing Mirror Configuration ────────────────────────
PRIMARY_MIRROR="http://ports.ubuntu.com/ubuntu-ports"
MAX_RETRIES_PER_MIRROR=2
MIRRORS_TRIED=()

is_checksum_failure() {
  grep -qE '(Hash Sum mismatch|Hash mismatch|checksum|Checksum|NO_PUBKEY|The following signatures couldn't be verified|Clearsigned file isn't valid|Bad header line|BADSIG)' "$build_log"
}

build_with_mirror() {
  local mirror_url="$1"
  APT_MIRROR="$mirror_url"

  # ── debootstrap stage 1 ───────────────────────────────────────
log "Running debootstrap stage 1..."

build_log="$(mktemp)"

debootstrap --arch="aarch64" --foreign --include=ca-certificates \
  "noble" "$ROOTFS" "$APT_MIRROR" 2>&1 | tee "$build_log"

# ── Copy QEMU for cross-arch ──────────────────────────────────
cp /usr/bin/qemu-aarch64-static "$ROOTFS/usr/bin/" 2>/dev/null || true

# ── debootstrap stage 2 ───────────────────────────────────────
log "Running debootstrap stage 2 (inside chroot)..."
chroot "$ROOTFS" /debootstrap/debootstrap --second-stage 2>&1 | tee -a "$build_log"

# ── APT sources ───────────────────────────────────────────────
log "Configuring APT sources..."
cat > "$ROOTFS/etc/apt/sources.list" << SOURCES_EOF
deb $APT_MIRROR noble main restricted universe multiverse
deb $APT_MIRROR noble-updates main restricted universe multiverse
deb $APT_MIRROR noble-security main restricted universe multiverse
SOURCES_EOF

# ── Install core packages ─────────────────────────────────────
log "Installing core packages..."
chroot "$ROOTFS" apt-get update -qq 2>&1 | tee -a "$build_log"
chroot "$ROOTFS" apt-get install -y \
  linux-raspi raspi-firmware u-boot-rpi flash-kernel \
  systemd-sysv sudo adduser locales \
  rpi-eeprom \
  gnome-shell gnome-session gdm3 gnome-control-center nautilus firefox chromium-browser vlc git cups network-manager cups bluez unattended-upgrades rpi-eeprom 2>&1 | tee -a "$build_log"
}

log "Starting self-healing build with primary mirror: ${PRIMARY_MIRROR}"

attempt=0
while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
  if [ "$attempt" -gt 0 ]; then
    log "Retrying primary mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${PRIMARY_MIRROR}"
    umount -R "$ROOTFS" 2>/dev/null || true
rm -rf "$ROOTFS"
mkdir -p "$ROOTFS"
mount "$LOOP_DEV"p2 "$ROOTFS"
mkdir -p "$ROOTFS/boot/firmware"
mount "$LOOP_DEV"p1 "$ROOTFS/boot/firmware"
  else
    log "Attempting build with primary mirror: ${PRIMARY_MIRROR}"
  fi

  MIRRORS_TRIED+=("${PRIMARY_MIRROR}")
  build_with_mirror "${PRIMARY_MIRROR}"; result=$?

  if [ "$result" -eq 0 ]; then
    rm -f "$build_log"
# ── config.txt ────────────────────────────────────────────────
log "Writing /boot/firmware/config.txt..."
CONFIG_TXT="${ROOTFS}/boot/firmware/config.txt"
echo "arm_64bit=1" >> "${CONFIG_TXT}"
echo "gpu_mem=128" >> "${CONFIG_TXT}"

# ── Enable services ───────────────────────────────────────────
log "Enabling systemd services..."
cat > "${ROOTFS}/tmp/enable-services.sh" << 'SVC_SCRIPT_EOF'
#!/bin/sh
set -e
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "unattended-upgrades.service" 2>/dev/null | grep -q "^unattended-upgrades.service"; then
  systemctl enable "unattended-upgrades.service"
else
  echo "Skipping unattended-upgrades.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "rpi-eeprom-update.service" 2>/dev/null | grep -q "^rpi-eeprom-update.service"; then
  systemctl enable "rpi-eeprom-update.service"
else
  echo "Skipping rpi-eeprom-update.service (unit not found - package may not be installed)"
fi
SVC_SCRIPT_EOF
chmod +x "${ROOTFS}/tmp/enable-services.sh"
chroot "${ROOTFS}" /tmp/enable-services.sh
rm -f "${ROOTFS}/tmp/enable-services.sh"

# ── Create default user ───────────────────────────────────────
log "Creating default user 'ubuntu'..."
: "${UBUNTU_PASSWORD:?Set UBUNTU_PASSWORD to the desired password for the ubuntu user before running this script.}"
chroot "${ROOTFS}" useradd -m -s /bin/bash -G sudo,adm ubuntu
printf '%s:%s
' "ubuntu" "${UBUNTU_PASSWORD}" | chroot "${ROOTFS}" chpasswd
chroot "${ROOTFS}" chage -d 0 ubuntu

# ── Hostname & fstab ──────────────────────────────────────────
echo "${DISTRO_NAME}" > "${ROOTFS}/etc/hostname"
BOOT_UUID=$(blkid -s UUID -o value "${LOOP_DEV}p1")
ROOT_UUID=$(blkid -s UUID -o value "${LOOP_DEV}p2")
cat > "${ROOTFS}/etc/fstab" << FSTAB_EOF
UUID=${BOOT_UUID}  /boot/firmware  vfat  defaults  0  2
UUID=${ROOT_UUID}  /               ext4  defaults  0  1
FSTAB_EOF

# ── Cleanup + unmount ─────────────────────────────────────────
log "Cleaning up..."
chroot "${ROOTFS}" apt-get clean
rm -f "${ROOTFS}/usr/bin/qemu-aarch64-static"
umount -R "${ROOTFS}"
losetup -d "${LOOP_DEV}"

# ── Compress ──────────────────────────────────────────────────
log "Compressing image..."
xz -T0 -z -k "${IMG_FILE}"
sha256sum "${IMG_FILE}.xz" > "${IMG_FILE}.xz.sha256"

log "Build complete!"
log "Image:    ${IMG_FILE}.xz"
log "Checksum: ${IMG_FILE}.xz.sha256"
log ""
log "# Flash to SD card:"
log "# xzcat ${IMG_FILE}.xz | sudo dd of=/dev/sdX bs=4M status=progress conv=fsync"
    exit 0
  fi

  if [ "$result" -ne 2 ]; then
    log "Build failed with non-checksum error. Not retrying."
    exit "$result"
  fi

  log "Checksum failure detected on primary mirror"
  attempt=$((attempt + 1))
done

log "Primary mirror exhausted after $((MAX_RETRIES_PER_MIRROR + 1)) attempts"

for fallback_mirror in "${FALLBACK_MIRRORS[@]}"; do
  log "Switching to fallback mirror: ${fallback_mirror}"
  umount -R "$ROOTFS" 2>/dev/null || true
rm -rf "$ROOTFS"
mkdir -p "$ROOTFS"
mount "$LOOP_DEV"p2 "$ROOTFS"
mkdir -p "$ROOTFS/boot/firmware"
mount "$LOOP_DEV"p1 "$ROOTFS/boot/firmware"

  attempt=0
  while [ "$attempt" -le "$MAX_RETRIES_PER_MIRROR" ]; do
    if [ "$attempt" -gt 0 ]; then
      log "Retrying fallback mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${fallback_mirror}"
      umount -R "$ROOTFS" 2>/dev/null || true
rm -rf "$ROOTFS"
mkdir -p "$ROOTFS"
mount "$LOOP_DEV"p2 "$ROOTFS"
mkdir -p "$ROOTFS/boot/firmware"
mount "$LOOP_DEV"p1 "$ROOTFS/boot/firmware"
    fi

    MIRRORS_TRIED+=("${fallback_mirror}")
    build_with_mirror "${fallback_mirror}"; result=$?

    if [ "$result" -eq 0 ]; then
      rm -f "$build_log"
# ── config.txt ────────────────────────────────────────────────
log "Writing /boot/firmware/config.txt..."
CONFIG_TXT="${ROOTFS}/boot/firmware/config.txt"
echo "arm_64bit=1" >> "${CONFIG_TXT}"
echo "gpu_mem=128" >> "${CONFIG_TXT}"

# ── Enable services ───────────────────────────────────────────
log "Enabling systemd services..."
cat > "${ROOTFS}/tmp/enable-services.sh" << 'SVC_SCRIPT_EOF'
#!/bin/sh
set -e
if systemctl list-unit-files "NetworkManager.service" 2>/dev/null | grep -q "^NetworkManager.service"; then
  systemctl enable "NetworkManager.service"
else
  echo "Skipping NetworkManager.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "cups.service" 2>/dev/null | grep -q "^cups.service"; then
  systemctl enable "cups.service"
else
  echo "Skipping cups.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "bluetooth.service" 2>/dev/null | grep -q "^bluetooth.service"; then
  systemctl enable "bluetooth.service"
else
  echo "Skipping bluetooth.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "unattended-upgrades.service" 2>/dev/null | grep -q "^unattended-upgrades.service"; then
  systemctl enable "unattended-upgrades.service"
else
  echo "Skipping unattended-upgrades.service (unit not found - package may not be installed)"
fi
if systemctl list-unit-files "rpi-eeprom-update.service" 2>/dev/null | grep -q "^rpi-eeprom-update.service"; then
  systemctl enable "rpi-eeprom-update.service"
else
  echo "Skipping rpi-eeprom-update.service (unit not found - package may not be installed)"
fi
SVC_SCRIPT_EOF
chmod +x "${ROOTFS}/tmp/enable-services.sh"
chroot "${ROOTFS}" /tmp/enable-services.sh
rm -f "${ROOTFS}/tmp/enable-services.sh"

# ── Create default user ───────────────────────────────────────
log "Creating default user 'ubuntu'..."
: "${UBUNTU_PASSWORD:?Set UBUNTU_PASSWORD to the desired password for the ubuntu user before running this script.}"
chroot "${ROOTFS}" useradd -m -s /bin/bash -G sudo,adm ubuntu
printf '%s:%s
' "ubuntu" "${UBUNTU_PASSWORD}" | chroot "${ROOTFS}" chpasswd
chroot "${ROOTFS}" chage -d 0 ubuntu

# ── Hostname & fstab ──────────────────────────────────────────
echo "${DISTRO_NAME}" > "${ROOTFS}/etc/hostname"
BOOT_UUID=$(blkid -s UUID -o value "${LOOP_DEV}p1")
ROOT_UUID=$(blkid -s UUID -o value "${LOOP_DEV}p2")
cat > "${ROOTFS}/etc/fstab" << FSTAB_EOF
UUID=${BOOT_UUID}  /boot/firmware  vfat  defaults  0  2
UUID=${ROOT_UUID}  /               ext4  defaults  0  1
FSTAB_EOF

# ── Cleanup + unmount ─────────────────────────────────────────
log "Cleaning up..."
chroot "${ROOTFS}" apt-get clean
rm -f "${ROOTFS}/usr/bin/qemu-aarch64-static"
umount -R "${ROOTFS}"
losetup -d "${LOOP_DEV}"

# ── Compress ──────────────────────────────────────────────────
log "Compressing image..."
xz -T0 -z -k "${IMG_FILE}"
sha256sum "${IMG_FILE}.xz" > "${IMG_FILE}.xz.sha256"

log "Build complete!"
log "Image:    ${IMG_FILE}.xz"
log "Checksum: ${IMG_FILE}.xz.sha256"
log ""
log "# Flash to SD card:"
log "# xzcat ${IMG_FILE}.xz | sudo dd of=/dev/sdX bs=4M status=progress conv=fsync"
      exit 0
    fi

    if [ "$result" -ne 2 ]; then
      log "Build failed with non-checksum error. Not retrying."
      exit "$result"
    fi

    log "Checksum failure detected on fallback mirror: ${fallback_mirror}"
    attempt=$((attempt + 1))
  done

  log "Fallback mirror exhausted: ${fallback_mirror}"
done

log "All mirrors exhausted after checksum failures. Mirrors tried:"
for m in "${MIRRORS_TRIED[@]}"; do
  log "  - ${m}"
done
die "Build failed after exhausting all mirrors"

