#!/usr/bin/env bash
# Example: Arch Linux + KDE + archiso + Calamares
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"
LOG_FILE="${OUTPUT_DIR}/build.log"
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}"
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${LOG_FILE}"
  log "Build directory: ${BUILD_DIR}"
  log "Output directory: ${OUTPUT_DIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ─────────────────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS.  The finished ISO
# is written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="archlinux:latest"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/var/tmp/distro-build \
    -e OUTPUT_DIR=/out \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
LOG_FILE="${OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

PROFILE_DIR="${BUILD_DIR}/profile"
WORK_DIR="${BUILD_DIR}/work"

# ── Prerequisites ─────────────────────────────────────────────────────────
log "Installing archiso..."
pacman -Syu --noconfirm --needed archiso calamares

# ── Copy baseline profile ────────────────────────────────────────────────
log "Setting up archiso profile..."
cp -r /usr/share/archiso/configs/releng "${PROFILE_DIR}"
cd "${PROFILE_DIR}"

# ── Package list ─────────────────────────────────────────────────────────
log "Writing package list..."
cat > packages.x86_64 << 'PKGS_EOF'
base
linux
linux-firmware
plasma-meta
kde-applications
sddm
firefox
vlc
git
flatpak
calamares
PKGS_EOF

# ── Airootfs overlay ─────────────────────────────────────────────────────
log "Writing airootfs overlay..."
mkdir -p airootfs/etc/systemd/system/multi-user.target.wants
ln -sf "/usr/lib/systemd/system/NetworkManager.service" \
  "airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
ln -sf "/usr/lib/systemd/system/sddm.service" \
  "airootfs/etc/systemd/system/multi-user.target.wants/sddm.service"

# ── Calamares config ─────────────────────────────────────────────────────
mkdir -p airootfs/etc/calamares
cat > airootfs/etc/calamares/settings.conf << 'CALA_EOF'
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:  [ partition, mount, unpackfs, machineid, fstab, locale,
             keyboard, localecfg, users, networkcfg, hwclock,
             services-systemd, grubcfg, bootloader, umount ]
  - show: [ finished ]
branding: MyDistro
CALA_EOF

# ── Build ────────────────────────────────────────────────────────────────
log "Building Arch ISO (this may take 20–40 minutes)..."
mkarchiso -v -w "${WORK_DIR}" -o "${OUTPUT_DIR}" "${PROFILE_DIR}"

log "Generating SHA256 checksum..."
find "${OUTPUT_DIR}" -name '*.iso' -exec sha256sum {} \; \
  > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
BUILT_ISO=$(find "${OUTPUT_DIR}" -maxdepth 1 -name '*.iso' | head -1)

log "Build complete!"
log "ISO:      ${BUILT_ISO}"
log "Checksum: ${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"

