#!/usr/bin/env bash
# ============================================================
# MyDistro — build-distro.sh
# Generated by https://fugginold.github.io/OSDB/
# Generator Version: 2026.04.29.1
# Generated At (UTC): 2026-05-03T05:18:09.345Z
# Builder: archiso
# ============================================================
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/var/tmp/distro-output}"
TMPDIR="${TMPDIR:-/var/tmp}"
HOST_OUTPUT_DIR="${HOST_OUTPUT_DIR:-}"
HOST_BUILD_DIR="${HOST_BUILD_DIR:-}"
LOG_FILE="${OUTPUT_DIR}/build.log"
DISPLAY_OUTPUT_DIR=""
DISPLAY_BUILD_DIR=""
DISPLAY_LOG_FILE=""
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|/work|/out|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}" || { log "Cleanup failed for path: ${cleanup_path}"; return 1; }
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${DISPLAY_LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${DISPLAY_LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${DISPLAY_LOG_FILE}"
  log "Build directory: ${DISPLAY_BUILD_DIR}"
  log "Output directory: ${DISPLAY_OUTPUT_DIR}"
  log "Temp directory: ${TMPDIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="archlinux:latest"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${BUILD_DIR}"):/work" \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/work/distro-build \
    -e OUTPUT_DIR=/out \
    -e TMPDIR=/var/tmp \
    -e HOST_BUILD_DIR="$(realpath "${BUILD_DIR}")" \
    -e HOST_OUTPUT_DIR="$(realpath "${OUTPUT_DIR}")" \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
mkdir -p "${TMPDIR}"
TMPDIR="$(cd "${TMPDIR}" && pwd -P)"
export TMPDIR TMP="${TMPDIR}" TEMP="${TMPDIR}"
LOG_FILE="${OUTPUT_DIR}/build.log"
if [ -n "${HOST_OUTPUT_DIR}" ]; then
  DISPLAY_OUTPUT_DIR="${HOST_OUTPUT_DIR}"
else
  DISPLAY_OUTPUT_DIR="${OUTPUT_DIR}"
fi
if [ -n "${HOST_BUILD_DIR}" ]; then
  DISPLAY_BUILD_DIR="${HOST_BUILD_DIR}"
else
  DISPLAY_BUILD_DIR="${BUILD_DIR}"
fi
DISPLAY_LOG_FILE="${DISPLAY_OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

PROFILE_DIR="${BUILD_DIR}/profile"
WORK_DIR="${BUILD_DIR}/work"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing archiso..."
pacman -Syu --noconfirm archiso calamares

# ── Copy baseline profile ──────────────────────────────────────
log "Setting up archiso profile..."
cp -r /usr/share/archiso/configs/releng "${PROFILE_DIR}"
cd "${PROFILE_DIR}"

# ── Package list ──────────────────────────────────────────────
log "Writing package list..."
cat > packages.x86_64 << 'PKGS_EOF'
plasma-meta
kde-applications
sddm
firefox
vlc
git
cups
networkmanager
cups
bluez
base
linux
linux-firmware
PKGS_EOF


# ── Calamares for Arch ─────────────────────────────────────────
log "Adding calamares to package list..."
echo "calamares" >> "${PROFILE_DIR}/packages.x86_64"
mkdir -p "${PROFILE_DIR}/airootfs/etc/calamares"
cat > "${PROFILE_DIR}/airootfs/etc/calamares/settings.conf" << 'CALA_EOF'
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:  [ partition, mount, unpackfs, machineid, fstab, locale,
             keyboard, localecfg, users, networkcfg, hwclock,
             services-systemd, grubcfg, bootloader, umount ]
  - show: [ finished ]
branding: MyDistro
CALA_EOF


# ── Airootfs overlay ───────────────────────────────────────────
log "Writing airootfs overlay..."
mkdir -p airootfs/etc/systemd/system/multi-user.target.wants
ln -sf "/usr/lib/systemd/system/NetworkManager.service" "airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
ln -sf "/usr/lib/systemd/system/cups.service" "airootfs/etc/systemd/system/multi-user.target.wants/cups.service"
ln -sf "/usr/lib/systemd/system/bluetooth.service" "airootfs/etc/systemd/system/multi-user.target.wants/bluetooth.service"

# ── Autologin ─────────────────────────────────────────────────
mkdir -p airootfs/root
if [ -f airootfs/root/customize_airootfs.sh ]; then
  cat >> airootfs/root/customize_airootfs.sh << 'AUTO_EOF'

# Configure display manager autologin

# Auto-login hook (SDDM)
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf << 'SDDM_EOF'
[Autologin]
User=user
Session=plasma
SDDM_EOF
AUTO_EOF
else
  cat > airootfs/root/customize_airootfs.sh << 'AUTO_EOF'
#!/bin/sh

# Configure display manager autologin

# Auto-login hook (SDDM)
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf << 'SDDM_EOF'
[Autologin]
User=user
Session=plasma
SDDM_EOF
AUTO_EOF
fi
chmod +x airootfs/root/customize_airootfs.sh

# ── Self-Healing Mirror Configuration ────────────────────────
PRIMARY_MIRROR="https://mirror.rackspace.com/archlinux"
FALLBACK_MIRRORS=("https://mirror.rackspace.com/archlinux" "https://mirrors.kernel.org/archlinux")
MIRRORS_TRIED=()
MAX_RETRIES_PER_MIRROR=2

build_with_mirror() {
  local mirror_base="$1"
  log "Configuring mirror: ${mirror_base}"

  # Write host container mirrorlist (pacman uses this during mkarchiso)
  printf 'Server = %s/$repo/os/$arch\n' "${mirror_base}" > /etc/pacman.d/mirrorlist

  # Write live-system mirrorlist (embedded in the ISO)
  mkdir -p "${PROFILE_DIR}/airootfs/etc/pacman.d"
  printf 'Server = %s/$repo/os/$arch\n' "${mirror_base}" > "${PROFILE_DIR}/airootfs/etc/pacman.d/mirrorlist"

  # Wipe work directory; PROFILE_DIR is preserved across retries
  rm -rf "${WORK_DIR}"

  local build_log
  build_log="$(mktemp)"

  if mkarchiso -v -w "${WORK_DIR}" -o "${OUTPUT_DIR}" "${PROFILE_DIR}" 2>&1 | tee "${build_log}"; then
    rm -f "${build_log}"
    return 0
  else
    if grep -qE '(FAILED|error: failed to commit transaction)' "${build_log}"; then
      rm -f "${build_log}"
      return 1
    else
      rm -f "${build_log}"
      return 2
    fi
  fi
}

log "Starting self-healing build with primary mirror: ${PRIMARY_MIRROR}"

# Try primary mirror with retries
for attempt in $(seq 0 ${MAX_RETRIES_PER_MIRROR}); do
  if [ "${attempt}" -eq 0 ]; then
    log "Attempting build with primary mirror: ${PRIMARY_MIRROR}"
  else
    log "Retrying primary mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${PRIMARY_MIRROR}"
  fi

  MIRRORS_TRIED+=("${PRIMARY_MIRROR}")

  if build_with_mirror "${PRIMARY_MIRROR}"; then
    log "Build succeeded with primary mirror"
    log "Generating SHA256 checksum..."
    find "${OUTPUT_DIR}" -name '*.iso' -exec sha256sum {} \; > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
    BUILT_ISO=$(find "${OUTPUT_DIR}" -maxdepth 1 -name '*.iso' | head -1)
    log "Build complete!"
    log "ISO:      ${BUILT_ISO}"
    log "Checksum: ${DISPLAY_OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
    exit 0
  fi

  build_result=$?
  if [ "${build_result}" -eq 2 ]; then
    log "Non-checksum build failure detected. Not retrying."
    log "Attempted mirrors: ${MIRRORS_TRIED[*]}"
    exit 1
  fi

  log "Checksum failure detected on primary mirror"
done

log "Primary mirror exhausted after $((MAX_RETRIES_PER_MIRROR + 1)) attempts"

# Try fallback mirrors
for fallback_mirror in "${FALLBACK_MIRRORS[@]}"; do
  log "Switching to fallback mirror: ${fallback_mirror}"

  for attempt in $(seq 0 ${MAX_RETRIES_PER_MIRROR}); do
    if [ "${attempt}" -gt 0 ]; then
      log "Retrying fallback mirror (attempt $((attempt + 1))/$((MAX_RETRIES_PER_MIRROR + 1))): ${fallback_mirror}"
    fi

    MIRRORS_TRIED+=("${fallback_mirror}")

    if build_with_mirror "${fallback_mirror}"; then
      log "Build succeeded with fallback mirror: ${fallback_mirror}"
      log "Generating SHA256 checksum..."
      find "${OUTPUT_DIR}" -name '*.iso' -exec sha256sum {} \; > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
      BUILT_ISO=$(find "${OUTPUT_DIR}" -maxdepth 1 -name '*.iso' | head -1)
      log "Build complete!"
      log "ISO:      ${BUILT_ISO}"
      log "Checksum: ${DISPLAY_OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
      exit 0
    fi

    build_result=$?
    if [ "${build_result}" -eq 2 ]; then
      log "Non-checksum build failure detected. Not retrying."
      log "Attempted mirrors: ${MIRRORS_TRIED[*]}"
      exit 1
    fi

    log "Checksum failure detected on fallback mirror: ${fallback_mirror}"
  done

  log "Fallback mirror exhausted: ${fallback_mirror}"
done

# All mirrors exhausted
log "ERROR: All mirrors exhausted. Build failed with checksum errors on all attempted mirrors."
log "Attempted mirrors (${#MIRRORS_TRIED[@]} total attempts):"
for tried_mirror in "${MIRRORS_TRIED[@]}"; do
  log "  - ${tried_mirror}"
done
exit 1
