#!/usr/bin/env bash
# Example: Arch Linux + KDE + archiso + Calamares
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"

PROFILE_DIR="${BUILD_DIR}/profile"
WORK_DIR="${BUILD_DIR}/work"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing archiso..."
pacman -Sy --noconfirm archiso calamares

# ── Copy baseline profile ──────────────────────────────────────
log "Setting up archiso profile..."
cp -r /usr/share/archiso/configs/releng "${PROFILE_DIR}"
cd "${PROFILE_DIR}"

# ── Package list ──────────────────────────────────────────────
log "Writing package list..."
cat > packages.x86_64 << 'PKGS_EOF'
base
linux
linux-firmware
plasma-meta
kde-applications
sddm
firefox
vlc
git
flatpak
calamares
PKGS_EOF

# ── Airootfs overlay ───────────────────────────────────────────
log "Writing airootfs overlay..."
mkdir -p airootfs/etc/systemd/system/multi-user.target.wants
ln -sf "/usr/lib/systemd/system/NetworkManager.service" \
  "airootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
ln -sf "/usr/lib/systemd/system/sddm.service" \
  "airootfs/etc/systemd/system/multi-user.target.wants/sddm.service"

# ── Calamares config ──────────────────────────────────────────
mkdir -p airootfs/etc/calamares
cat > airootfs/etc/calamares/settings.conf << 'CALA_EOF'
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:  [ partition, mount, unpackfs, machineid, fstab, locale,
             keyboard, localecfg, users, networkcfg, hwclock,
             services-systemd, grubcfg, bootloader, umount ]
  - show: [ finished ]
branding: MyDistro
CALA_EOF

# ── Build ──────────────────────────────────────────────────────
log "Building Arch ISO (this may take 20–40 minutes)..."
mkarchiso -v -w "${WORK_DIR}" -o "${OUTPUT_DIR}" "${PROFILE_DIR}"

log "Generating SHA256 checksum..."
find "${OUTPUT_DIR}" -name '*.iso' -exec sha256sum {} \; \
  > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"

log "Build complete! Output: ${OUTPUT_DIR}"
