#!/usr/bin/env bash
# Example: Debian 12 Bookworm + KDE + live-build + Calamares
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"
LOG_FILE="${OUTPUT_DIR}/build.log"
CLEANUP_ON_FAILURE="${CLEANUP_ON_FAILURE:-true}"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
SCRIPT_START_DIR="$(pwd -P)"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup_build_dir() {
  case "${CLEANUP_ON_FAILURE}" in
    1|true|TRUE|yes|YES) ;;
    *) log "Leaving build directory in place because CLEANUP_ON_FAILURE=${CLEANUP_ON_FAILURE}"; return 0 ;;
  esac

  if [ ! -f "${BUILD_MARKER}" ]; then
    log "Skipping cleanup; build marker not found in ${BUILD_DIR}"
    return 0
  fi

  local cleanup_path output_path
  cleanup_path="$(cd "$(dirname "${BUILD_DIR}")" && pwd -P)/$(basename "${BUILD_DIR}")" || return 0
  output_path="$(cd "$(dirname "${OUTPUT_DIR}")" && pwd -P)/$(basename "${OUTPUT_DIR}")" || output_path="${OUTPUT_DIR}"

  case "${cleanup_path}" in
    /|/tmp|/var|/var/tmp|/home|"${HOME:-}") log "Refusing to clean unsafe BUILD_DIR: ${cleanup_path}"; return 0 ;;
  esac
  if [ "${cleanup_path}" = "${SCRIPT_START_DIR}" ]; then
    log "Refusing to clean BUILD_DIR because it is the launch directory: ${cleanup_path}"
    return 0
  fi
  case "${output_path}" in
    "${cleanup_path}"|"${cleanup_path}"/*) log "Refusing to clean BUILD_DIR because it contains OUTPUT_DIR: ${output_path}"; return 0 ;;
  esac

  log "Removing failed build workspace: ${cleanup_path}"
  rm -rf --one-file-system -- "${cleanup_path}"
}
finish_build() {
  local status=$?
  if [ "${status}" -ne 0 ]; then
    log "Build failed with exit code ${status}. See ${LOG_FILE}"
    cleanup_build_dir
  else
    log "Build log saved to ${LOG_FILE}"
  fi
}
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${LOG_FILE}"
  log "Build directory: ${BUILD_DIR}"
  log "Output directory: ${OUTPUT_DIR}"
  log "Cleanup on failure: ${CLEANUP_ON_FAILURE}"
  trap finish_build EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="debian:bookworm"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/var/tmp/distro-build \
    -e OUTPUT_DIR=/out \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
BUILD_DIR="$(cd "${BUILD_DIR}" && pwd -P)"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd -P)"
LOG_FILE="${OUTPUT_DIR}/build.log"
BUILD_MARKER="${BUILD_DIR}/.osdb-build-workspace"
: > "${BUILD_MARKER}"
start_logging

LB_DIR="${BUILD_DIR}/lb"

ensure_live_build_workdir() {
  local path="$1"
  local mount_opts

  mkdir -p "${path}"
  if ! command -v findmnt >/dev/null 2>&1; then
    return 0
  fi

  mount_opts="$(findmnt -T "${path}" -no OPTIONS 2>/dev/null || true)"
  case ",${mount_opts}," in
    *,nodev,*|*,noexec,*)
      die "BUILD_DIR '${path}' is on a filesystem mounted with ${mount_opts}. live-build/debootstrap needs device nodes and executable scripts. Re-run with BUILD_DIR=/var/tmp/distro-build or another directory on a normal filesystem (ext4/xfs)."
      ;;
  esac
}

ensure_live_build_workdir "${BUILD_DIR}"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing live-build..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y live-build curl ca-certificates

mkdir -p "${LB_DIR}"
cd "${LB_DIR}"

# ── lb config ─────────────────────────────────────────────────
log "Configuring live-build..."
lb config \
  --distribution "bookworm" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --binary-images iso-hybrid \
  --bootloader "grub-efi,syslinux" \
  --debian-installer none \
  --apt-recommends false \
  --memtest none

# ── Chroot environment ──────────────────────────────
log "Setting noninteractive environment for chroot..."
mkdir -p config
printf '%s\n' \
  'DEBIAN_FRONTEND=noninteractive' \
  'DEBCONF_NONINTERACTIVE_SEEN=true' > config/environment.chroot

# ── Debconf preseed ──────────────────────────────
log "Writing debconf preseed..."
mkdir -p config/preseed
cat > config/preseed/live.cfg.chroot << 'PRESEED_EOF'
console-setup console-setup/charmap47 select UTF-8
console-setup console-setup/codeset47 select Guess optimal character set
console-setup console-setup/fontface47 select Fixed
console-setup console-setup/fontsize-fb47 select 8x16
console-setup console-setup/store_defaults_in_debconf_db boolean true
keyboard-configuration keyboard-configuration/modelcode string pc105
keyboard-configuration keyboard-configuration/layout select English (US)
keyboard-configuration keyboard-configuration/layoutcode string us
keyboard-configuration keyboard-configuration/variant select
keyboard-configuration keyboard-configuration/variantcode string
keyboard-configuration keyboard-configuration/xkb-keymap select us
PRESEED_EOF

# ── Package lists ──────────────────────────────────────────────
log "Writing package lists..."
mkdir -p config/package-lists
printf '%s\n' \
  "kde-plasma-desktop" "plasma-nm" "plasma-pa" "kscreen" "sddm" \
  "network-manager" "bluez" \
  > config/package-lists/desktop.list.chroot

printf '%s\n' \
  "firefox-esr" "vlc" "git" "cups" "flatpak" \
  > config/package-lists/user.list.chroot

printf '%s\n' "live-boot" "live-config" "live-config-systemd" \
  > config/package-lists/live.list.chroot

printf '%s\n' "calamares" "calamares-settings-debian" \
  > config/package-lists/installer.list.chroot

# ── Chroot hooks ───────────────────────────────────────────────
log "Writing chroot hooks..."
mkdir -p config/hooks/live

cat > config/hooks/live/0010-services.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
enable_if_exists() {
  systemctl list-unit-files --quiet "$1" 2>/dev/null | grep -q "^$1" && \
    systemctl enable "$1" || echo "Skipping $1 (unit not found)"
}
enable_if_exists "NetworkManager.service"
enable_if_exists "cups.service"
enable_if_exists "bluetooth.service"
HOOK_EOF
chmod +x config/hooks/live/0010-services.hook.chroot

cat > config/hooks/live/0020-autologin.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf << 'SDDM_EOF'
[Autologin]
User=user
Session=plasma
SDDM_EOF
HOOK_EOF
chmod +x config/hooks/live/0020-autologin.hook.chroot

# ── Calamares config ──────────────────────────────────────────
log "Writing Calamares configuration..."
CALA_DIR="${LB_DIR}/config/includes.chroot/etc/calamares"
mkdir -p "${CALA_DIR}/branding/MyDistro" "${CALA_DIR}/modules"

cat > "${CALA_DIR}/settings.conf" << 'CALA_EOF'
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:  [ partition, mount, unpackfs, machineid, fstab, locale,
             keyboard, localecfg, users, networkcfg, hwclock,
             services-systemd, grubcfg, bootloader, packages,
             removeuser, umount ]
  - show: [ finished ]
branding: MyDistro
prompt-install: false
dont-chroot: false
CALA_EOF

cat > "${CALA_DIR}/modules/users.conf" << 'USERS_EOF'
---
defaultGroups: [ users, lp, video, audio, cdrom, plugdev, netdev ]
autologinGroup: autologin
sudoersGroup: sudo
setRootPassword: false
USERS_EOF

# ── Build ──────────────────────────────────────────────────────
log "Starting live-build (this may take 30–60 minutes)..."
lb build

find . -maxdepth 1 -name '*.iso' -exec mv {} "${OUTPUT_DIR}/${DISTRO_NAME}.iso" \;

log "Generating SHA256 checksum..."
sha256sum "${OUTPUT_DIR}/${DISTRO_NAME}.iso" > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"

log "Build complete!"
log "ISO:      ${OUTPUT_DIR}/${DISTRO_NAME}.iso"
log "Checksum: ${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
