#!/usr/bin/env bash
# Example: Debian 12 Bookworm + KDE + live-build + Calamares
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Debian ISO from an Arch Linux host).  The finished ISO / IMG is
# written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="debian:bookworm"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/tmp/distro-build \
    -e OUTPUT_DIR=/out \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  die "This script must be run as root. Re-run with: sudo $0"
fi

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"

LB_DIR="${BUILD_DIR}/lb"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing live-build..."
apt-get update -qq
apt-get install -y live-build curl ca-certificates calamares

mkdir -p "${LB_DIR}"
cd "${LB_DIR}"

# ── lb config ─────────────────────────────────────────────────
log "Configuring live-build..."
lb config \
  --distribution "bookworm" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --binary-images iso-hybrid \
  --bootloaders "grub-efi,syslinux" \
  --debian-installer none \
  --apt-recommends false \
  --memtest none

# ── Package lists ──────────────────────────────────────────────
log "Writing package lists..."
mkdir -p config/package-lists
printf '%s\n' \
  "kde-plasma-desktop" "plasma-nm" "plasma-pa" "kscreen" "sddm" \
  > config/package-lists/desktop.list.chroot

printf '%s\n' \
  "firefox-esr" "vlc" "git" "cups" "flatpak" \
  > config/package-lists/user.list.chroot

printf '%s\n' "live-boot" "live-config" "live-config-systemd" \
  > config/package-lists/live.list.chroot

printf '%s\n' "calamares" "calamares-settings-debian" \
  > config/package-lists/installer.list.chroot

# ── Chroot hooks ───────────────────────────────────────────────
log "Writing chroot hooks..."
mkdir -p config/hooks/live

cat > config/hooks/live/0010-services.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
systemctl enable "NetworkManager.service"
systemctl enable "cups.service"
systemctl enable "bluetooth.service"
HOOK_EOF
chmod +x config/hooks/live/0010-services.hook.chroot

cat > config/hooks/live/0020-autologin.hook.chroot << 'HOOK_EOF'
#!/bin/sh
set -e
mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf.d/autologin.conf << 'SDDM_EOF'
[Autologin]
User=user
Session=plasma
SDDM_EOF
HOOK_EOF
chmod +x config/hooks/live/0020-autologin.hook.chroot

# ── Calamares config ──────────────────────────────────────────
log "Writing Calamares configuration..."
CALA_DIR="${LB_DIR}/config/includes.chroot/etc/calamares"
mkdir -p "${CALA_DIR}/branding/MyDistro" "${CALA_DIR}/modules"

cat > "${CALA_DIR}/settings.conf" << 'CALA_EOF'
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:  [ partition, mount, unpackfs, machineid, fstab, locale,
             keyboard, localecfg, users, networkcfg, hwclock,
             services-systemd, grubcfg, bootloader, packages,
             removeuser, umount ]
  - show: [ finished ]
branding: MyDistro
prompt-install: false
dont-chroot: false
CALA_EOF

cat > "${CALA_DIR}/modules/users.conf" << 'USERS_EOF'
---
defaultGroups: [ users, lp, video, audio, cdrom, plugdev, netdev ]
autologinGroup: autologin
sudoersGroup: sudo
setRootPassword: false
USERS_EOF

# ── Build ──────────────────────────────────────────────────────
log "Starting live-build (this may take 30–60 minutes)..."
lb build 2>&1 | tee "${OUTPUT_DIR}/build.log"

find . -maxdepth 1 -name '*.iso' -exec mv {} "${OUTPUT_DIR}/${DISTRO_NAME}.iso" \;

log "Generating SHA256 checksum..."
sha256sum "${OUTPUT_DIR}/${DISTRO_NAME}.iso" > "${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"

log "Build complete!"
log "ISO:      ${OUTPUT_DIR}/${DISTRO_NAME}.iso"
log "Checksum: ${OUTPUT_DIR}/${DISTRO_NAME}.iso.sha256"
