#!/usr/bin/env bash
# Example: Raspberry Pi OS Lite (Bookworm) — headless, pi-gen
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/var/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"
LOG_FILE="${OUTPUT_DIR}/build.log"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }
die() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
start_logging() {
  mkdir -p "${OUTPUT_DIR}"
  : > "${LOG_FILE}"
  exec > >(tee -a "${LOG_FILE}") 2>&1
  log "Logging to ${LOG_FILE}"
  log "Build directory: ${BUILD_DIR}"
  log "Output directory: ${OUTPUT_DIR}"
  trap 'status=$?; if [ "$status" -ne 0 ]; then log "Build failed with exit code $status. See ${LOG_FILE}"; else log "Build log saved to ${LOG_FILE}"; fi' EXIT
}

# ── Container self-re-launch ──────────────────────────────────
# If this script is not already running inside a container it
# re-execs itself inside the correct build environment using
# Docker or Podman, so it works on any host OS (e.g. building a
# Raspberry Pi OS image from an Arch Linux host).  The finished
# IMG is written to OUTPUT_DIR on the host via a bind-mount.
# --privileged is required for loop-device and chroot operations.
CONTAINER_IMAGE="debian:bookworm"

if [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
  if command -v docker >/dev/null 2>&1; then
    _RUNTIME=docker
  elif command -v podman >/dev/null 2>&1; then
    _RUNTIME=podman
  else
    die "Docker or Podman is required to build on a non-native host. Install Docker: https://docs.docker.com/engine/install/ -- or Podman: https://podman.io/docs/installation"
  fi
  _SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
  if [[ "${_SCRIPT_SOURCE}" != */* ]]; then
    _SCRIPT_SOURCE="$(command -v -- "${_SCRIPT_SOURCE}" || true)"
  fi
  [ -n "${_SCRIPT_SOURCE}" ] || die "Unable to resolve script path for container re-exec"
  _SCRIPT_PATH="$(realpath "${_SCRIPT_SOURCE}")" || die "Unable to canonicalize script path: ${_SCRIPT_SOURCE}"
  log "Re-launching inside ${CONTAINER_IMAGE} via ${_RUNTIME}..."
  mkdir -p "${OUTPUT_DIR}"
  exec "${_RUNTIME}" run --rm --privileged \
    -v "$(realpath "${OUTPUT_DIR}"):/out" \
    -v "${_SCRIPT_PATH}:/build.sh:ro" \
    -e BUILD_DIR=/var/tmp/distro-build \
    -e OUTPUT_DIR=/out \
    "${CONTAINER_IMAGE}" bash /build.sh
fi

# This script is designed to be run as a normal user with sudo available.
# Privileged operations (apt-get, build.sh) use sudo explicitly.

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"
start_logging

PIGEN_DIR="${BUILD_DIR}/pi-gen"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing pi-gen dependencies..."
sudo apt-get update -qq
sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree \
  zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc gpg

# ── Clone pi-gen ──────────────────────────────────────────────
log "Cloning pi-gen..."
if [ -d "${PIGEN_DIR}" ]; then
  git -C "${PIGEN_DIR}" pull
else
  git clone https://github.com/RPi-Distro/pi-gen.git "${PIGEN_DIR}"
fi
cd "${PIGEN_DIR}"

# ── User password ─────────────────────────────────────────────
# Set PIGEN_USER_PASS env var before running, or it defaults to "raspberry".
# WARNING: the default password is insecure — change it for production images.
: "${PIGEN_USER_PASS:=raspberry}"

# ── Main config ───────────────────────────────────────────────
log "Writing pi-gen config..."
cat > config << CONFIG_EOF
IMG_NAME="MyDistro"
RELEASE="bookworm"
LOCALE_DEFAULT="en_US.UTF-8"
KEYBOARD_KEYMAP="us"
KEYBOARD_LAYOUT="English (US)"
TIMEZONE_DEFAULT="America/New_York"
FIRST_USER_NAME="pi"
FIRST_USER_PASS="${PIGEN_USER_PASS}"
ENABLE_SSH=1
STAGE_LIST="stage0 stage1 stage2 stage-custom"
CONFIG_EOF

# Lite build — skip desktop stages
touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES

# ── Custom stage: packages ────────────────────────────────────
log "Writing custom stage..."
mkdir -p stage-custom/01-packages
printf '%s' "git curl vim htop raspi-config rpi-eeprom" \
  > stage-custom/01-packages/packages

# ── Custom stage: services + config.txt ──────────────────────
mkdir -p stage-custom/03-run
cat > stage-custom/03-run/01-run.sh << 'RUN_EOF'
#!/bin/bash
on_chroot << 'CHROOT'
set -e
systemctl enable "ssh.service"
systemctl enable "NetworkManager.service"
systemctl enable "rpi-eeprom-update.service"
systemctl enable "raspi-config.service"

CONFIG_TXT="/boot/firmware/config.txt"
[ -f "${CONFIG_TXT}" ] || CONFIG_TXT="/boot/config.txt"
echo "arm_64bit=1" >> "${CONFIG_TXT}"
echo "gpu_mem=128" >> "${CONFIG_TXT}"
CHROOT
RUN_EOF
chmod +x stage-custom/03-run/01-run.sh

# ── Build ──────────────────────────────────────────────────────
log "Starting pi-gen build (this may take 30–90 minutes)..."
sudo ./build.sh

LATEST_XZ=$(find deploy -name '*.img.xz' | head -1)
LATEST_IMG=$(find deploy -name '*.img' -not -name '*.img.xz' | head -1)
[ -n "${LATEST_XZ}"  ] && cp "${LATEST_XZ}"  "${OUTPUT_DIR}/${DISTRO_NAME}.img.xz" || true
[ -n "${LATEST_IMG}" ] && cp "${LATEST_IMG}" "${OUTPUT_DIR}/${DISTRO_NAME}.img"    || true

log "Build complete! Output: ${OUTPUT_DIR}"
log ""
log "# Flash to SD card (replace /dev/sdX with your device):"
log "# xzcat ${OUTPUT_DIR}/${DISTRO_NAME}.img.xz | sudo dd of=/dev/sdX bs=4M status=progress conv=fsync"
