#!/usr/bin/env bash
# Example: Raspberry Pi OS Lite (Bookworm) — headless, pi-gen
# Used as a static ShellCheck reference — generated by OSDB wizard
set -euo pipefail

DISTRO_NAME="MyDistro"
BUILD_DIR="${BUILD_DIR:-/tmp/distro-build}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/distro-output}"

log() { printf '\033[1;34m[%s]\033[0m %s\n' "$(date +%T)" "$*"; }

mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"

PIGEN_DIR="${BUILD_DIR}/pi-gen"

# ── Prerequisites ─────────────────────────────────────────────
log "Installing pi-gen dependencies..."
apt-get update -qq
apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree \
  zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc gpg

# ── Clone pi-gen ──────────────────────────────────────────────
log "Cloning pi-gen..."
if [ -d "${PIGEN_DIR}" ]; then
  git -C "${PIGEN_DIR}" pull
else
  git clone https://github.com/RPi-Distro/pi-gen.git "${PIGEN_DIR}"
fi
cd "${PIGEN_DIR}"

# ── Main config ───────────────────────────────────────────────
log "Writing pi-gen config..."
cat > config << 'CONFIG_EOF'
IMG_NAME="MyDistro"
RELEASE="bookworm"
LOCALE_DEFAULT="en_US.UTF-8"
KEYBOARD_KEYMAP="us"
KEYBOARD_LAYOUT="English (US)"
TIMEZONE_DEFAULT="America/New_York"
FIRST_USER_NAME="pi"
FIRST_USER_PASS="raspberry"
ENABLE_SSH=1
STAGE_LIST="stage0 stage1 stage2 stage-custom"
CONFIG_EOF

# Lite build — skip desktop stages
touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES

# ── Custom stage: packages ────────────────────────────────────
log "Writing custom stage..."
mkdir -p stage-custom/01-packages
printf '%s' "git curl vim htop raspi-config rpi-eeprom" \
  > stage-custom/01-packages/packages

# ── Custom stage: services + config.txt ──────────────────────
mkdir -p stage-custom/03-run
cat > stage-custom/03-run/01-run.sh << 'RUN_EOF'
#!/bin/bash
on_chroot << 'CHROOT'
set -e
systemctl enable "ssh.service"
systemctl enable "NetworkManager.service"
systemctl enable "rpi-eeprom-update.service"
systemctl enable "raspi-config.service"

CONFIG_TXT="/boot/firmware/config.txt"
[ -f "${CONFIG_TXT}" ] || CONFIG_TXT="/boot/config.txt"
echo "arm_64bit=1" >> "${CONFIG_TXT}"
echo "gpu_mem=128" >> "${CONFIG_TXT}"
CHROOT
RUN_EOF
chmod +x stage-custom/03-run/01-run.sh

# ── Build ──────────────────────────────────────────────────────
log "Starting pi-gen build (this may take 30–90 minutes)..."
sudo ./build.sh 2>&1 | tee "${OUTPUT_DIR}/build.log"

LATEST_XZ=$(find deploy -name '*.img.xz' | head -1)
LATEST_IMG=$(find deploy -name '*.img' -not -name '*.img.xz' | head -1)
[ -n "${LATEST_XZ}"  ] && cp "${LATEST_XZ}"  "${OUTPUT_DIR}/${DISTRO_NAME}.img.xz" || true
[ -n "${LATEST_IMG}" ] && cp "${LATEST_IMG}" "${OUTPUT_DIR}/${DISTRO_NAME}.img"    || true

log "Build complete! Output: ${OUTPUT_DIR}"
log ""
log "# Flash to SD card (replace /dev/sdX with your device):"
log "# xzcat ${OUTPUT_DIR}/${DISTRO_NAME}.img.xz | sudo dd of=/dev/sdX bs=4M status=progress conv=fsync"
